window.FC26_LATEST = "javascript:(function(){fetch('https://justaino.com/releases/latest.js?t='+Date.now()).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(function(c){(0,eval)(c)}).catch(function(e){alert('Justaino FC Hub could not load: '+e.message)})})();";
window.FC26_VERSIONS = [
  {
    "v": 39,
    "date": "2026-07-31",
    "note": "Suggest now picks the PlayStyles that actually raise your score, instead of reading off a fixed list. It works one slot at a time, and it judges each candidate by building the card you WOULD have and scoring that - so a suggestion isn't a guess about the score, it is the score. Three things follow from that. It re-measures after every pick, because what a PlayStyle is worth depends on what's already on the card. It stops as soon as nothing left would move the number, so it won't fill slots for the sake of it - if it picks 5 and leaves 3 basic slots free, those slots genuinely add nothing. And it will spend a PlayStyle+ upgrading a good PlayStyle the card already has when that beats adding a new one, which also hands the basic slot back for it to refill. The big one: if you've set your own PlayStyle weights for a position in Peks Lab, Suggest now follows YOURS. Before this you could rank your whole club by your own weighting and Suggest would still hand you mine. It builds for the role you actually picked rather than whichever role flatters the card, and the status line tells you what it chose and what your score does: 4 PS+, 1 basic, score 40.2 to 89.7",
    "code": "javascript:(function(){fetch('https://justaino.com/releases/v39.js?t='+Date.now()).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(function(c){(0,eval)(c)}).catch(function(e){alert('Justaino FC Hub could not load: '+e.message)})})();"
  },
  {
    "v": 38,
    "date": "2026-07-31",
    "note": "Fixes the slot counts when you upgrade a PlayStyle you already had. If a card held Finesse and Power Shot as basics and you applied Finesse+, it read as 1 PlayStyle+ and 2 basics - it should be 1 and 1, because applying the + upgrades that slot rather than adding a second one, and gives the basic back. Two things were wrong: the panel briefly held the same PlayStyle as both a basic and a +, and the meters took whichever count was higher, which kept the stale basic. A PlayStyle is now held once, as either the basic or the +, with the + always winning; and while the panel is holding receipts for a card it trusts its own count, since the game's numbers lag both ways after an upgrade. The deck agrees too: the tile flips straight to gold, and the freed basic slot is available again immediately",
    "code": "javascript:(function(){fetch('https://justaino.com/releases/v38.js?t='+Date.now()).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(function(c){(0,eval)(c)}).catch(function(e){alert('Justaino FC Hub could not load: '+e.message)})})();"
  },
  {
    "v": 37,
    "date": "2026-07-30",
    "note": "Peks specifically said that the new icons are ugly AF, such a shame but ah well. So the diamonds are gone and the original square PlayStyle tiles are back - but the categories stay, so the deck is still grouped under the six headings (Finishing, Passing, Defending, Ball control, Physical, Goalkeeping) with a tally of what the card holds in each. The PlayStyle+/Basic tabs are gone too: there's now one tile per PlayStyle and a tap cycles it - once to queue the basic, twice for the PlayStyle+, a third time to clear it. Any step the card can't take is left out of the cycle, so a tap can never land somewhere the game would reject: a card that already has the basic goes straight to PS+, and with a cap full that kind is skipped. A queued tile carries a strip along the bottom saying which kind it's queued as, BASIC in cyan or PS+ in gold, so the second tap is never a guess - and nothing is spent until you press Apply. A gold tile with a tick means the card already has the PlayStyle+, a tinted tile with a tick means it has the basic. Suggest is untouched and still picks exactly what it did before, except its picks now light up across the whole deck at once instead of being split over two tabs",
    "code": "javascript:(function(){fetch('https://justaino.com/releases/v37.js?t='+Date.now()).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(function(c){(0,eval)(c)}).catch(function(e){alert('Justaino FC Hub could not load: '+e.message)})})();"
  }
];
